---

- name: "download installer"
  uri:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: /tmp/nvm-install.sh
    mode: +x
    status_code:
      - 200
      - 304

- name: "install"
  shell: /tmp/nvm-install.sh
