---

- name: install
  become: true
  pacman:
    name: vscode
    state: present

- name: ensure settings directory exists
  file:
    path: "~/.config/Code - OSS/User/settings.json"
    state: directory

- name: copy settings preset
  copy:
    src: settings.json
    mode: 664
    dest: "~/.config/Code - OSS/User/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
