---

- name: install
  community.general.pacman:
    name: vscode
    state: present

- name: copy settings preset
  copy:
    src: settings.json
    mode: 664
    dest: "~/.config/Code - OSS/User/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
