---
- hosts: localhost
  connection: local
  roles:
    - ohmyzsh
    - vscode
    - google-chrome
    - nodejs
    - docker
    - nvm
    - aws-cli
    - kubectl
    - terraform
    - imagemagick
    # - i3
    - redshift
    - steam
    - guake
    - postman
    # - rust
    - lazygit
