---

- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add apt key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: install docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: add user to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker
    append: yes
