---

- name: check if ohmyzsh folder exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_folder

- name: download script
  uri:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    mode: +x
    dest: /tmp/ohmyzsh.sh
  when: not ohmyzsh_folder.stat.exists

- name: install
  shell: /tmp/ohmyzsh.sh
  when: not ohmyzsh_folder.stat.exists

- name: clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: 1
    dest: ~/.oh-my-zsh/themes/powerlevel10k
  become_user: "{{ lookup('env', 'USER') }}"

- name: install p10k config
  copy:
    src: p10k.zsh
    dest: ~/.p10k.zsh

- name: replace zsh config
  copy:
    src: .zshrc
    dest: ~/.zshrc
